# Jekyll configuration for GitHub Pages
permalink: pretty
plugins:
  - jekyll-sitemap

# Remove .html extension from URLs
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      permalink: /:basename/

# Include all files
include:
  - _pages
  - _data

# Exclude development files and prevent Jekyll from processing assets
exclude:
  - "*.py"
  - "venv/"
  - "excel_sample.csv"
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/

# Keep Jekyll from processing these files
keep_files:
  - assets
  - js
  - styles.css

# Disable Jekyll processing for static assets
plugins:
  - jekyll-sitemap

# Ensure CSS and JS are served correctly
sass:
  style: compressed

# Markdown settings (minimal to avoid conflicts)
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false